// Minimal shim for the Adafruit GFXfont bitmap-font format. We ship
// fonts pre-converted from TTF using Adafruit's `fontconvert` tool
// (output lives next to this header, e.g. FreeSans18pt7b.h). Those
// headers reference these two struct types and a PROGMEM macro. We
// don't want to drag in the full Adafruit_GFX dependency just for the
// type names, so this header provides:
//
//   * PROGMEM   - empty on ESP32 (flash-resident const data is the
//                 default; the Arduino/AVR distinction doesn't apply).
//   * GFXglyph  - per-character metrics (one entry per ASCII codepoint
//                 in the font's range): width / height of the bitmap,
//                 advance to next-char x, baseline-relative origin
//                 offset, and offset into the shared bitmap byte array.
//   * GFXfont   - top-level font handle: pointers to the bitmap and
//                 glyph arrays, first / last covered codepoints (0x20
//                 .. 0x7E for a 7-bit ASCII font), and yAdvance (the
//                 baseline-to-baseline line height in destination
//                 pixels).
//
// The bitmap is 1 bit per pixel, packed MSB-first into a stream of
// bytes; each glyph occupies (width * height + 7) / 8 bytes starting
// at `bitmapOffset` in the shared array. Reader code walks the stream
// bit by bit and maps each lit bit to a destination pixel using the
// glyph's width / height / xOffset / yOffset.
//
// Layout matches Adafruit's reference exactly (Adafruit-GFX-Library /
// gfxfont.h), so any font header generated by Adafruit's fontconvert
// drops in unchanged once `#include <Adafruit_GFX.h>` is rewritten to
// `#include "gfx_font.h"`.

#pragma once

#include <stdint.h>

#ifndef PROGMEM
#define PROGMEM
#endif

typedef struct {
    uint16_t bitmapOffset;  // start byte of this glyph's bitmap within bitmap[]
    uint8_t  width;         // bitmap width in pixels
    uint8_t  height;        // bitmap height in pixels
    uint8_t  xAdvance;      // pen-position advance to the next character
    int8_t   xOffset;       // x-distance from cursor to top-left of bitmap
    int8_t   yOffset;       // y-distance from baseline to top of bitmap (negative = above)
} GFXglyph;

typedef struct {
    uint8_t  *bitmap;       // packed 1bpp bitmap stream, shared across glyphs
    GFXglyph *glyph;        // per-codepoint metrics array, indexed by (codepoint - first)
    uint16_t  first;        // first covered codepoint
    uint16_t  last;         // last covered codepoint (inclusive)
    uint8_t   yAdvance;     // baseline-to-baseline distance, in destination pixels
} GFXfont;
