"""Generate a C++ header embedding ``src/web/index.html`` as a pre-gzipped
byte array. Runs as a PlatformIO ``pre:`` extra script so the header is
always up to date before the C++ compile starts.

Why pre-gzipped: the page compresses to roughly a third of its source
size. Shipping the compressed bytes with a ``Content-Encoding: gzip``
header off-loads compression to the build host and cuts wifi airtime
on every page load. The IDF http server doesn't compress on the fly,
so without this every request would push the raw HTML.

Why this is here rather than ``target_add_binary_data`` / ``EMBED_TXTFILES``:
both of those upstream ESP-IDF helpers walk through
``idf_build_get_property(BUILD_DIR)`` which PIO returns as a *relative*
path. CMake then re-resolves that against ``CMAKE_CURRENT_BINARY_DIR``,
producing a doubled ``.pio/build/<env>/.pio/build/<env>/...`` path that
the generated asm rule can't find. Same root-cause as the ESP-DL model
embed bug worked around in ``scripts/flash_espdl_models.py``.

The generated header is gitignored and lives next to its source, so
editing the HTML feels like editing a normal asset file: change
``src/web/index.html``, the next build regenerates the header, the next
firmware boot serves the new page.
"""

# SCons exposes the PIO build environment via dependency injection.
Import("env")  # noqa: F821  pylint: disable=undefined-variable

import gzip
from pathlib import Path

PROJECT_DIR = Path(env["PROJECT_DIR"])  # noqa: F821
SRC_DIR     = PROJECT_DIR / "src" / "web"
HTML_PATH   = SRC_DIR / "index.html"
HEADER_PATH = SRC_DIR / "index_html_data.h"

# Level 9 buys a few percent over 6 on text and is essentially free at
# build time for a file this size.
GZIP_LEVEL = 9


def generate_header() -> None:
    # Normalise line endings before compressing so the output is
    # bit-identical regardless of git's autocrlf setting on Windows.
    raw = HTML_PATH.read_text(encoding="utf-8").replace("\r\n", "\n").encode("utf-8")

    # mtime=0 strips the modification-time field from the gzip header
    # (Python 3.8+). Without this every build produces a different blob
    # even when the HTML hasn't changed, defeating the rewrite-only-on-
    # change short-circuit below and forcing a webserver.cpp recompile
    # on every build.
    gz = gzip.compress(raw, compresslevel=GZIP_LEVEL, mtime=0)

    body_lines = []
    for i in range(0, len(gz), 16):
        chunk = gz[i:i + 16]
        body_lines.append("    " + ", ".join(f"0x{b:02x}" for b in chunk) + ",")
    body = "\n".join(body_lines)

    ratio = (len(gz) / len(raw) * 100.0) if raw else 0.0
    header = (
        "// AUTO-GENERATED by scripts/embed_web_html.py from src/web/index.html.\n"
        "// Do not edit. Edit the HTML file instead -- the next build will\n"
        "// regenerate this header.\n"
        "//\n"
        f"// Source size: {len(raw)} B   gzip size: {len(gz)} B   ratio: {ratio:.1f}%\n"
        "//\n"
        "// Deterministic blob (level 9, mtime=0) -- the file is rewritten\n"
        "// only when the HTML actually changes, so downstream recompiles\n"
        "// of webserver.cpp are skipped on no-op builds.\n"
        "#pragma once\n"
        "\n"
        "#include <cstddef>\n"
        "#include <cstdint>\n"
        "\n"
        "namespace web {\n"
        "inline constexpr std::uint8_t index_html_gz[] = {\n"
        f"{body}\n"
        "};\n"
        "inline constexpr std::size_t index_html_gz_len = sizeof(index_html_gz);\n"
        "} // namespace web\n"
    )

    # Only rewrite if the contents actually changed -- avoids forcing a
    # downstream recompile of webserver.cpp on every build.
    if HEADER_PATH.exists() and HEADER_PATH.read_text(encoding="utf-8") == header:
        return
    HEADER_PATH.write_text(header, encoding="utf-8")
    print(
        f"embed_web_html: regenerated {HEADER_PATH.relative_to(PROJECT_DIR)}"
        f" ({len(raw)} B -> {len(gz)} B gz)"
    )


generate_header()
