"""Generate a C++ header embedding ``src/web/index.html`` as a pre-gzipped
byte array.

Usage:
    python embed_web_html.py <input.html> <output_header.h>

Invoked from ``src/CMakeLists.txt`` as a build-time CMake custom command
so the header is always up to date before the C++ compile starts.

Why pre-gzipped: the page compresses to roughly a third of its source
size. Shipping the compressed bytes with a ``Content-Encoding: gzip``
header off-loads compression to the build host and cuts wifi airtime
on every page load. The IDF http server doesn't compress on the fly,
so without this every request would push the raw HTML.

Why this rather than ``target_add_binary_data`` / ``EMBED_TXTFILES``:
those upstream ESP-IDF helpers embed the file's raw bytes verbatim with
no compression. Pre-gzipping on the build host lets the firmware ship the
page at roughly a third of its size and serve it with a
``Content-Encoding: gzip`` header, so this small custom generator earns
its keep.

The generated header is gitignored and lives next to its source, so
editing the HTML feels like editing a normal asset file: change
``src/web/index.html``, the next build regenerates the header, the next
firmware boot serves the new page.
"""

import gzip
import sys
from pathlib import Path

# Level 9 buys a few percent over 6 on text and is essentially free at
# build time for a file this size.
GZIP_LEVEL = 9


def generate_header(html_path: Path, header_path: Path) -> None:
    # Normalise line endings before compressing so the output is
    # bit-identical regardless of git's autocrlf setting on Windows.
    raw = html_path.read_text(encoding="utf-8").replace("\r\n", "\n").encode("utf-8")

    # mtime=0 strips the modification-time field from the gzip header
    # (Python 3.8+). Without this every build produces a different blob
    # even when the HTML hasn't changed, defeating the rewrite-only-on-
    # change short-circuit below and forcing a webserver.cpp recompile
    # on every build.
    gz = gzip.compress(raw, compresslevel=GZIP_LEVEL, mtime=0)

    body_lines = []
    for i in range(0, len(gz), 16):
        chunk = gz[i:i + 16]
        body_lines.append("    " + ", ".join(f"0x{b:02x}" for b in chunk) + ",")
    body = "\n".join(body_lines)

    ratio = (len(gz) / len(raw) * 100.0) if raw else 0.0
    header = (
        "// AUTO-GENERATED by scripts/embed_web_html.py from src/web/index.html.\n"
        "// Do not edit. Edit the HTML file instead -- the next build will\n"
        "// regenerate this header.\n"
        "//\n"
        f"// Source size: {len(raw)} B   gzip size: {len(gz)} B   ratio: {ratio:.1f}%\n"
        "//\n"
        "// Deterministic blob (level 9, mtime=0) -- the file is rewritten\n"
        "// only when the HTML actually changes, so downstream recompiles\n"
        "// of webserver.cpp are skipped on no-op builds.\n"
        "#pragma once\n"
        "\n"
        "#include <cstddef>\n"
        "#include <cstdint>\n"
        "\n"
        "namespace web {\n"
        "inline constexpr std::uint8_t index_html_gz[] = {\n"
        f"{body}\n"
        "};\n"
        "inline constexpr std::size_t index_html_gz_len = sizeof(index_html_gz);\n"
        "} // namespace web\n"
    )

    # Only rewrite if the contents actually changed -- avoids forcing a
    # downstream recompile of webserver.cpp on every build.
    if header_path.exists() and header_path.read_text(encoding="utf-8") == header:
        return
    header_path.parent.mkdir(parents=True, exist_ok=True)
    header_path.write_text(header, encoding="utf-8")
    print(
        f"embed_web_html: regenerated {header_path.name}"
        f" ({len(raw)} B -> {len(gz)} B gz)"
    )


def main(argv: list[str]) -> int:
    if len(argv) != 3:
        print(
            "usage: embed_web_html.py <input.html> <output_header.h>",
            file=sys.stderr,
        )
        return 2
    generate_header(Path(argv[1]), Path(argv[2]))
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
