"""Generate a C++ header embedding ``src/web/index.html`` as a raw-string
literal. Runs as a PlatformIO ``pre:`` extra script so the header is
always up to date before the C++ compile starts.

Why this is here rather than ``target_add_binary_data`` / ``EMBED_TXTFILES``:
both of those upstream ESP-IDF helpers walk through
``idf_build_get_property(BUILD_DIR)`` which PIO returns as a *relative*
path. CMake then re-resolves that against ``CMAKE_CURRENT_BINARY_DIR``,
producing a doubled ``.pio/build/<env>/.pio/build/<env>/...`` path that
the generated asm rule can't find. Same root-cause as the ESP-DL model
embed bug worked around in ``scripts/flash_espdl_models.py``.

The generated header is gitignored and lives next to its source, so
editing the HTML feels like editing a normal asset file: change
``src/web/index.html``, the next build regenerates the header, the next
firmware boot serves the new page.
"""

# SCons exposes the PIO build environment via dependency injection.
Import("env")  # noqa: F821  pylint: disable=undefined-variable

from pathlib import Path

PROJECT_DIR = Path(env["PROJECT_DIR"])  # noqa: F821
SRC_DIR     = PROJECT_DIR / "src" / "web"
HTML_PATH   = SRC_DIR / "index.html"
HEADER_PATH = SRC_DIR / "index_html_data.h"

# Raw-string delimiter. C++ caps this at 16 characters; we use a short
# token unlikely to appear in HTML / CSS / JS. The generator below
# verifies the token doesn't collide with the input.
DELIM = "WEBHTML"


def generate_header() -> None:
    html = HTML_PATH.read_text(encoding="utf-8")
    if f"){DELIM}\"" in html:
        raise RuntimeError(
            f"raw-string delimiter '{DELIM}' collides with index.html content;"
            " pick a different delimiter."
        )

    header = (
        "// AUTO-GENERATED by scripts/embed_web_html.py from src/web/index.html.\n"
        "// Do not edit. Edit the HTML file instead -- the next build will\n"
        "// regenerate this header.\n"
        "#pragma once\n"
        "\n"
        "#include <cstddef>\n"
        "\n"
        "namespace web {\n"
        f"inline constexpr char index_html[] = R\"{DELIM}(\n"
        f"{html})"
        f"{DELIM}\";\n"
        "inline constexpr std::size_t index_html_len = sizeof(index_html) - 1;\n"
        "} // namespace web\n"
    )

    # Only rewrite if the contents actually changed -- avoids forcing a
    # downstream recompile of webserver.cpp on every build.
    if HEADER_PATH.exists() and HEADER_PATH.read_text(encoding="utf-8") == header:
        return
    HEADER_PATH.write_text(header, encoding="utf-8")
    print(f"embed_web_html: regenerated {HEADER_PATH.relative_to(PROJECT_DIR)}")


generate_header()
